#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

rm -rf ellipsoid3D_MachineLearningMeshMotionInput
rm -rf ellipsoid3D_MachineLearningMeshMotion
rm -rf ellipsoid3D_LaplaceMeshMotion

#------------------------------------------------------------------------------
