#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

cleanCase
rm -rf 0

#------------------------------------------------------------------------------
